# Configure JPA
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

